### ISSUE TITLE
Swift 4 Support

### ISSUE THREAD

**Issue by neetrath** [btnguyen2k/swiftutils#4]
Found 

"Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions" 

at "queryFilter" Property

and maybe some other errors in Swift 4, Xcode 9

**Comment by btnguyen2k** [comment]
Hi @neetrath, @fizzy871 has fixed "Expression was too complex to be solved..." in the latest PR.

Cheers,
